### ISSUE TITLE
Any chance of fixing the mouse aim?

### ISSUE THREAD

**Issue by Gibitwit** [atsb/NakedAVP#10]
You know.
Dead zone moving mouse forward.
Dead zone moving mouse right.
Aim acceleration.
Sensitivity is different for each species do to scaling proportionally with the different FOV of each species.

Would be nice to set a specific value from a console or config file rather than the ampbiguous sliders.

Work was started on this in the port AVPx.  http://homepage.eircom.net/~duncandsl/avp/

**Comment by atsb** [comment]
I'll take a look at that source and see if it can be merged in.

**Comment by Gibitwit** [comment]
Cool, hopefully the mouse aim is totally fixed some day.

**Comment by atsb** [comment]
I'll do this today..  Urgh, I hate it when people use such horrible version control systems..  assembla makes me want to rip my hair out :D
